#!/usr/bin/env sh
################################################################################
# Prototype: webcam live stream with ffmpeg direted to a local icecast server.

# An icecast server must be setup with the following minimal mount point
# configuration:

# <mount type="normal">
#   <mount-name>/iot-lab</mount-name>
#   <stream-name>KNX</stream-name>
#   <max-listeners>1</max-listeners>
#   <burst-size>65536</burst-size>
#   <public>0</public>
# </mount>
################################################################################
# globals
_ihost=localhost
_iport=8000
_istream=iot-lab

usage=$(cat <<EOF


Usage:

  $0 USER PASSWORD [IHOST [PORT [STREAM]]]

where:

  USER      User name for the icecast connection
  PASSWORD  Password for the icecast connection
  IHOST     Icecast hostname. Default: ${_ihost}
  PORT      Icecast port. Default: ${_iport}
  STERAM    Icecast stream nane. Default: ${_istream}
EOF
)

user=${1:?"arg #1 missing: user name for the icecast connection. ${usage}"}
password=${2:?"arg #2 missing: password for the icecast connection. ${usage}"}
ihost=${3:-${_ihost}}
port=${4:-${_iport}}
stream=${5:-${_istream}}


ffmpeg -f v4l2 -video_size 640x480 -framerate 25 -i /dev/video0  -f webm \
       -cluster_size_limit 2M -cluster_time_limit 5100 \
       -content_type video/webm -c:v libvpx -b:v 500K -crf 30 -g 100 \
       -deadline good -threads 4\
       icecast://${user}:${password}@${ihost}:${port}/${stream}
